server: 
  port: 8080

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          expiration: 3600000
          issuer-uri: http://localhost:8083/auth/realms/baeldung
          jwk-set-uri: http://localhost:8083/auth/realms/baeldung/protocol/openid-connect/certs